# Generated by Django 3.1.3 on 2020-11-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0006_delete_dulieu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dulieudauvao',
        ),
        migrations.DeleteModel(
            name='dulieuhocmay',
        ),
    ]
