# Generated by Django 3.1.3 on 2020-12-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0008_dulieudauvao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dulieudauvao',
            name='thoigian',
            field=models.DateTimeField(),
        ),
    ]
