# Generated by Django 3.1.3 on 2020-12-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0009_auto_20201209_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dulieudauvao',
            name='thoigian',
            field=models.IntegerField(),
        ),
    ]
