# Generated by Django 3.1.3 on 2020-12-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0010_auto_20201209_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dulieudauvao',
            name='thoigian',
            field=models.DateTimeField(),
        ),
    ]
