# Generated by Django 3.1.3 on 2020-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0012_wdudoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wdudoan',
            name='wsonguoi',
            field=models.FloatField(),
        ),
    ]
