# Generated by Django 3.1.3 on 2020-12-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0013_auto_20201209_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wdudoan',
        ),
    ]
