# Generated by Django 3.1.3 on 2020-12-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0016_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='API',
        ),
    ]
