# Generated by Django 3.1.3 on 2020-12-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0022_dulieudauvao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wdudoan',
        ),
    ]
