# Generated by Django 3.1.3 on 2020-12-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0024_wdudoan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='API',
        ),
    ]
