# Generated by Django 3.1.3 on 2020-12-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0026_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='API',
        ),
        migrations.DeleteModel(
            name='dulieudauvao',
        ),
        migrations.DeleteModel(
            name='Wdudoan',
        ),
    ]
