# Generated by Django 3.1.3 on 2020-12-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0028_api_dulieudauvao_wdudoan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wdudoan',
        ),
    ]
