# Generated by Django 3.1.3 on 2020-12-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0031_thingspeak'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='thingspeak',
            new_name='thingspeaks',
        ),
    ]
