# Generated by Django 3.1.3 on 2020-12-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0032_auto_20201221_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='theongay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigian', models.DateField()),
                ('luongnuocdodac', models.FloatField()),
                ('luongnuocdudoan', models.FloatField()),
            ],
        ),
    ]
